# Generated by Django 4.0.5 on 2022-06-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('proc', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=200)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('mem', models.IntegerField()),
                ('mem_vive', models.IntegerField()),
                ('serveur_lancement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appserv.serveur')),
            ],
        ),
        migrations.AddField(
            model_name='serveur',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appserv.type'),
        ),
        migrations.CreateModel(
            name='appli',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name_app', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('serveur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appserv.serveur')),
                ('utilisateur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appserv.utilisateur')),
            ],
        ),
    ]
