# Generated by Django 4.0.5 on 2022-06-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserv', '0002_alter_appli_serveur_alter_appli_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appli',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
